sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eBBXSrc5sQkk95y8S6Ettav8gPQPcADGrTaoGVN2wQDJUQCHBUUrTFu9PCWgD3kaQbP8HnbODUl4uPs5yGL/9XEmbignk3wVFw1avgozvz/Nf1PIedhRk/20HEEomJvS6AxH1zonrYII56VR6eE9PFV1/O92EIV0ZjHu7tMbCMpm0sbjWTvJSx9b447B7p2XMP4P28VexRvEYUMuGW56oU/l/YwiUjRv49uaCfj3RsQJljAvtTLvC0S0b8u+3LYSQbMR686etoq3xXvSvgkhzO4WIxpQ1Ek/63QhqB2DMenSDBkGEnfdtXp9zmli6mEfbehVguylUcJeVSAhAE8zr/AkmFZLVkFysdH67c8EPOdLLWnSKejTMcdE5UGpo3/Jn7fWGiqgJq9iSzPdI3zp+sN5YA9L0eAC99OsXzlIH7MtBtuoFO1zHG3NpWtftc0Gg3OeyNcY5NYjdVeIps99lu8PNjkm0BZbj2Rrk20qJpsW+egYQ8YHTJHp2TaKhm/mjY3Ud2h3ZhS89uU6MLAg53D4k10l4DJhmWAFSbDF0dc6u4Jd4p4ZzZiUxn5nNBlxn3OIsfO/bbyGh1u7ObYC/SXM9sVJpbt950wI87Uio6BR4OnWyldO6F06DLvJqUO2wiv1UJSzd7gyh7mHqHjTqVTjIOkllK0TI34DYBm89Yk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Trent-s-Trust-and-Other-Stories_2459
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy